### ISSUE TITLE
Windows SimpleITK installer test

### ISSUE THREAD

**Issue by fabien-w** [SimpleITK/SimpleITKRInstaller#18]
Hi,
I have test the installer in windows and it does not work. 
Did you plan to update this function for windows ?
Thanks,
Fabien

**Comment by blowekamp** [comment]
Thank you for reporting the issue. The problem did you encounter? Do you have the complete error message?

Currently we are aware of the memory limitation of the R toolchain's linker that we are encountering.

We have been discussing the proper solution for windows. There are open pull requests SimpleITK/SimpleITK#243 and SimpleITK/SimpleITK#195 who are looking into how to address this issue. It will involve not using the R tool change but  the latest mingw64 toolchain.

**Comment by fabien-w** [comment]
Hi Bradley, thank you very much for your reply
There are no visible errors, but it seems that there is no installation of
simple itk.
After the installation i have a R package but R cannot find the ITK
function
Here a copy of the console during installation :


> devtools::install_github("SimpleITK/SimpleITKRInstaller",force = TRUE)
Downloading GitHub repo SimpleITK/SimpleITKRInstaller@master
from URL
https://api.github.com/repos/SimpleITK/SimpleITKRInstaller/zipball/master
Installing SimpleITK
"C:/PROGRA~1/R/R-33~1.1/bin/x64/R" --no-site-file --no-environ --no-save
--no-restore  \
  --quiet CMD INSTALL  \

"C:/Users/fabie/AppData/Local/Temp/RtmpQXY5vL/devtools19385b995996/SimpleITK-SimpleITKRInstaller-5f821a0"
 \
  --library="C:/Users/fabie/Documents/R/win-library/3.3" --install-tests

* installing *source* package 'SimpleITK' ...

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************


** help
No man pages found in package  'SimpleITK'
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (SimpleITK)
> library(SimpleITK)
> Image
Error: object 'Image' not found

2017-08-17 14:09 GMT-03:00 Bradley Lowekamp <notifications@github.com>:

**Comment by richardbeare** [comment]
The installer package will require some extra work to function under Windows. I have looked at this briefly, but it is a long way off. The limitation is the requirement for non-standard tool chains, as SimpleITK is too large and results in crashes of RTools compilers. This means a user will need to install a set of software and configure it before using the installer, preventing it being an easy option as is the case under linux, where the tools are available by default. Current focus is a build procedure that we are happy with using standard mechanisms.
