### ISSUE TITLE
installation failed:

### ISSUE THREAD

**Issue by aminemosbah** [SimpleITK/SimpleITKRInstaller#44]
devtools::install_github("SimpleITK/SimpleITKRInstaller",force=TRUE)
Downloading GitHub repo SimpleITK/SimpleITKRInstaller@master
√  checking for file 'C:\Windows\Temp\RtmpQRsOTu\remotes9ec392b442f\SimpleITK-SimpleITKRInstaller-c9a5c99/DESCRIPTION' ...
-  preparing 'SimpleITK':
√  checking DESCRIPTION meta-information ...
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  creating default NAMESPACE file
-  building 'SimpleITK_1.2.3.tar.gz'
   Warning: file 'SimpleITK/configure' did not have execute permissions: corrected
   
Installing package into ‘C:/software/Rpackages’
(as ‘lib’ is unspecified)
* installing *source* package 'SimpleITK' ...
** using staged installation

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************

**Comment by richardbeare** [comment]
Looks like you're attempting to install under windows. This doesn't work yet! We have had limited success completing a build using the new RTools/RTesting distributions, but haven't managed to have the tests run correctly.

**Comment by aminemosbah** [comment]
absolutely, any suggestion please?

**Comment by richardbeare** [comment]
Not for the moment. It is something we're working on.
