### ISSUE TITLE
Compilation of cFS fails due to cmake error detecting functional CXX compiler

### ISSUE THREAD

**Issue by javich8597** [SimpleITK/SimpleITKRInstaller#46]
Hello I am new to this world, and I have encountered this problem when rebuilding the cFS files using the make command, I have compiler uninstalled and updated.
Someone could help me?

javi@javi-HP-Laptop-14-cf1xxx:~/OpenSatKit-master/cfs$ make
mkdir -p "build"
(cd "build/" && cmake  -DCMAKE_INSTALL_PREFIX=/exe -DCMAKE_BUILD_TYPE=debug "/home/javi/OpenSatKit-master/cfs/cfe")
-- Module 'cfs_lib' found at /home/javi/OpenSatKit-master/cfs/apps/cfs_lib
-- Module 'expat_lib' found at /home/javi/OpenSatKit-master/cfs/apps/expat_lib
-- Module 'osk_c_fw' found at /home/javi/OpenSatKit-master/cfs/apps/osk_c_fw
-- Module 'osk_cpp_fw' found at /home/javi/OpenSatKit-master/cfs/apps/osk_cpp_fw
-- Module 'cs' found at /home/javi/OpenSatKit-master/cfs/apps/cs
-- Module 'ds' found at /home/javi/OpenSatKit-master/cfs/apps/ds
-- Module 'fm' found at /home/javi/OpenSatKit-master/cfs/apps/fm
-- Module 'hs' found at /home/javi/OpenSatKit-master/cfs/apps/hs
-- Module 'kit_ci' found at /home/javi/OpenSatKit-master/cfs/apps/kit_ci
-- Module 'kit_sch' found at /home/javi/OpenSatKit-master/cfs/apps/kit_sch
-- Module 'kit_to' found at /home/javi/OpenSatKit-master/cfs/apps/kit_to
-- Module 'lc' found at /home/javi/OpenSatKit-master/cfs/apps/lc
-- Module 'md' found at /home/javi/OpenSatKit-master/cfs/apps/md
-- Module 'mm' found at /home/javi/OpenSatKit-master/cfs/apps/mm
-- Module 'sc' found at /home/javi/OpenSatKit-master/cfs/apps/sc
-- Module 'hk' found at /home/javi/OpenSatKit-master/cfs/apps/hk
-- Module 'tftp' found at /home/javi/OpenSatKit-master/cfs/apps/tftp
-- Module 'i42' found at /home/javi/OpenSatKit-master/cfs/apps/i42
-- Module 'f42' found at /home/javi/OpenSatKit-master/cfs/apps/f42
-- Module 'isim' found at /home/javi/OpenSatKit-master/cfs/apps/isim
-- Module 'hc' found at /home/javi/OpenSatKit-master/cfs/apps/hc
-- Module 'hsim' found at /home/javi/OpenSatKit-master/cfs/apps/hsim
-- Module 'osk_c_demo' found at /home/javi/OpenSatKit-master/cfs/apps/osk_c_demo
-- Module 'osk_cpp_demo' found at /home/javi/OpenSatKit-master/cfs/apps/osk_cpp_demo
-- Module 'cfe-core' found at /home/javi/OpenSatKit-master/cfs/cfe/fsw/cfe-core
-- Module 'osal' found at /home/javi/OpenSatKit-master/cfs/osal
-- Configuring for system arch: cpu1
-- OSAL Selection: posix
-- OSAL Compile Definitions: -Wall -m32  -D_XOPEN_SOURCE=600   
-- OSAL Link Libraries: pthread;dl;rt
-- PSP Selection: pc-linux
-- Building App: cfs_lib install=cpu1
-- Building App: expat_lib install=cpu1
-- Building App: osk_c_fw install=cpu1
-- Building App: osk_cpp_fw install=cpu1
-- The CXX compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- broken
CMake Error at /usr/share/cmake-3.10/Modules/CMakeTestCXXCompiler.cmake:45 (message):
  The C++ compiler

    "/usr/bin/g++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/javi/OpenSatKit-master/cfs/build/cpu1/CMakeFiles/CMakeTmp
    
    Run Build Command:"/usr/bin/make" "cmTC_47c5f/fast"
    make[1]: se entra en el directorio '/home/javi/OpenSatKit-master/cfs/build/cpu1/CMakeFiles/CMakeTmp'
    /usr/bin/make -f CMakeFiles/cmTC_47c5f.dir/build.make CMakeFiles/cmTC_47c5f.dir/build
    make[2]: se entra en el directorio '/home/javi/OpenSatKit-master/cfs/build/cpu1/CMakeFiles/CMakeTmp'
    Building CXX object CMakeFiles/cmTC_47c5f.dir/testCXXCompiler.cxx.o
    /usr/bin/g++    -m32  -D_XOPEN_SOURCE=600       -o CMakeFiles/cmTC_47c5f.dir/testCXXCompiler.cxx.o -c /home/javi/OpenSatKit-master/cfs/build/cpu1/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
    Linking CXX executable cmTC_47c5f
    /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_47c5f.dir/link.txt --verbose=1
    /usr/bin/g++  -m32  -D_XOPEN_SOURCE=600        -rdynamic CMakeFiles/cmTC_47c5f.dir/testCXXCompiler.cxx.o  -o cmTC_47c5f 
    /usr/bin/ld: se salta el /usr/lib/gcc/x86_64-linux-gnu/7/libstdc++.so incompatible mientras se busca -lstdc++
    /usr/bin/ld: se salta el /usr/lib/gcc/x86_64-linux-gnu/7/libstdc++.a incompatible mientras se busca -lstdc++
    /usr/bin/ld: no se puede encontrar -lstdc++
    collect2: error: ld returned 1 exit status
    CMakeFiles/cmTC_47c5f.dir/build.make:97: recipe for target 'cmTC_47c5f' failed
    make[2]: *** [cmTC_47c5f] Error 1
    make[2]: se sale del directorio '/home/javi/OpenSatKit-master/cfs/build/cpu1/CMakeFiles/CMakeTmp'
    Makefile:126: recipe for target 'cmTC_47c5f/fast' failed
    make[1]: *** [cmTC_47c5f/fast] Error 2
    make[1]: se sale del directorio '/home/javi/OpenSatKit-master/cfs/build/cpu1/CMakeFiles/CMakeTmp'
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  /home/javi/OpenSatKit-master/cfs/apps/osk_cpp_fw/CMakeLists.txt:2 (project)

-- Configuring incomplete, errors occurred!
See also "/home/javi/OpenSatKit-master/cfs/build/cpu1/CMakeFiles/CMakeOutput.log".
See also "/home/javi/OpenSatKit-master/cfs/build/cpu1/CMakeFiles/CMakeError.log".
CMake Error at cmake/mission_build.cmake:344 (message):
  Failed to configure cpu1
Call Stack (most recent call first):
  CMakeLists.txt:113 (process_arch)

-- Configuring incomplete, errors occurred!
See also "/home/javi/OpenSatKit-master/cfs/build/CMakeFiles/CMakeOutput.log".
Makefile:120: recipe for target 'build/.prep' failed
make: *** [build/.prep] Error 1

**Comment by zivy** [comment]
Hello @javich8597,

Your posting on our issue tracker is unrelated to the SimpleITK toolkit's R installer or to SimpleITK. 

You are compiling OpenSatKit, you need to ask this on [their issue tracker](https://github.com/OpenSatKit/OpenSatKit/issues).
